apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pacman
spec:
  rules:
    - host: ${APPLICATION_FQDN}
      http:
        paths:
          - backend:
            path: /
            pathType: ImplementationSpecific
              service:
                name: pacman
                port: 
                  number: 80
